// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfabokblsjglymrwiyth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmYWJva2Jsc2pnbHltcndpeXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjM2MzIsImV4cCI6MjA2MDMzOTYzMn0.Vzd4Er32b-CTJEOORHD5ZRhNRiF2UezAN2adnRBkDM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});